apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
- apiGroups:
    - extensions
    - networking.k8s.io
    - traefik.containo.us
    - traefik.io
  resources:
    - ingresses
    - ingressroutes
  verbs:
    - get
    - watch
    - list
