apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-ingres-to-avahi-deployment
spec:
  selector:
    matchLabels:
      app: k8s-ingres-to-avahi
  template:
    metadata:
      labels:
        app: k8s-ingres-to-avahi
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
      - name: main
        image: {{ .Values.image }}
        args:
          - --hostname
          - {{ .Values.hostname }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /var/run/dbus
          name: dbus
      volumes:
      - name: dbus
        hostPath:
          path: /var/run/dbus
          type: Directory
