apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingres-reader
subjects:
- kind: ServiceAccount
  name: k8s-ingres-to-avahi
  namespace: default
roleRef:
  kind: Role
  name: ingres-reader
  apiGroup: rbac.authorization.k8s.io
