name: Build & Push to GHCR

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}

      - name: Build
        run: |
          docker buildx build \
            . \
            --platform linux/arm64 \
            --tag ghcr.io/${{github.repository}}:latest
            --output type=image,push=false

      - name: Push
        run: |
          docker buildx build \
            . \
            --platform linux/arm64 \
            --tag ghcr.io/${{github.repository}}:latest
            --output type=image,push=true
