name: Build & Push to GHCR

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{github.repository}}

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.IMAGE_NAME }}:cache
            ${{ github.github.ref_type == "branch" && ("type=registry,ref=" + env.IMAGE_NAME + ":cache-" + github.ref_name) || "" }}
          cache-to: |
            type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max
            ${{ github.github.ref_type == "branch" && ("type=registry,ref=" + env.IMAGE_NAME + ":cache-" + github.ref_name) || "" }},mode=max
